### ISSUE TITLE
libjemalloc2 package missing

### ISSUE THREAD

**Issue by albundy83** [stargate/docker-images#128]
Hello,

using the latest image available (v1.0.72), it will be nice to have `libjemalloc2` package installed.
It seems missing, here the warning message:
```
WARN  [main] 2023-01-22 17:49:47,191 StartupChecks.java:143 - jemalloc shared library could not be preloaded to speed up memory allocations
```
A small update in Dockerfiles at "apt install" command will be perfect:
 `apt install curl unzip iproute2 libaio1 -y` to  `apt install curl unzip iproute2 libaio1 libjemalloc2 -y`

Thanks for your help

**Comment by tatu-at-datastax** [comment]
I assume this explains background too?

https://github.com/bitnami/charts/issues/6087

Sounds reasonable.

**Comment by jeffreyscarpenter** [comment]
Thanks @albundy83, looks like a helpful change. We'll look into this for the v1 releases. Also note that most of our efforts are going to v2 at this point. For v2 the dockerfiles are in the main`stargate/stargate` repo, so we'll investigate making this change there as well.
