### ISSUE TITLE
Stargate multi-arch support for M1 development (arm64v8)

### ISSUE THREAD

**Issue by pgobin** [stargate/docker-images#47]
### Issue Type
Bug

### Description
Stargate images do not support `arm64v8` architecture. This is required for running Stargate in a Docker container on M1 MacBook Pros. Without `arm64v8` multi-arch support, local development is not currently possible.

### System
**Machine:** Apple M1 MacBook Pro (Big Sur)
**Docker:** Docker Desktop Preview 3.1.0 (https://docs.docker.com/docker-for-mac/apple-m1/)
**Image:** stargateio/stargate-3_11:v1.0.14

### Steps
1.  From [the official stargate documentation](https://stargate.io/docs/stargate/1.0/developers-guide/install/install_cass_3x.html).

Run:

```
docker run --name stargate \
  -p 8080:8080 \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION=3.11 \
  -e DEVELOPER_MODE=true \
  stargateio/stargate-3_11:v1.0.14
``` 
2. Process exits with error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Please add multi-arch support for M1 machines. Not every developer has access to remote infrastructure for testing.

Thanks!

**Comment by dougwettlaufer** [comment]
Hi @pgobin thanks for bringing this up. We're all split across Linux and older macs, would you be willing to help out with testing?

**Comment by pgobin** [comment]
@dougwettlaufer Absolutely.

**Comment by eddiejaoude** [comment]
I have this issue also, any movement or ETA on this? I am happy to test too. Thank you 🤓

**Comment by dougwettlaufer** [comment]
@pgobin and @eddiejaoude I just pushed [v1.0.27-m1_test2](https://hub.docker.com/layers/stargateio/stargate-3_11/v1.0.27-m1_test2/images/sha256-423e873e777f0e45572d28b5d29546585c2a24291940376127887218554a88d8?context=explore) which should now support Apple M1. When you get a chance would you mind trying it out and letting me know how it works on your machines?

**Comment by eddiejaoude** [comment]
Thanks @dougwettlaufer , as a quick glance it seems to work fine on the M1 👍

**Comment by eddiejaoude** [comment]
I have been using this image for a few days and all seems fine 💥 Thank you!

**Comment by dougwettlaufer** [comment]
Awesome, thanks for confirming @eddiejaoude
