### ISSUE TITLE
Automatically create PR for a new stargate release

### ISSUE THREAD

**Issue by ivansenic** [stargate/docker-images#58]
Once a new version is released on stargate/stargate we should create a new PR for this repository automatically. In order to do this:

* ~create script that replaces the version in all necessary files~ done in #59 
* create webhook that can be trigger from the stargate/stargate (pass new version as the payload)
* create workflow that creates a new  PR based on the new version of Stargate and is fired on the webhook call
* extend Stargate release workflow to ping the webhook using [peter-evans/repository-dispatch](https://github.com/peter-evans/repository-dispatch)

**Comment by tatu-at-datastax** [comment]
Done for Stargate V2 so I think this can be closed.
