### ISSUE TITLE
shell script error in example

### ISSUE THREAD

**Issue by LordJohar** [stargate/docker-images#60]
Hi
I found an error in your example in [this file](https://github.com/stargate/docker-images/blob/master/examples/cassandra-3.11/start_cass_311.sh).
In /bin/sh `[[` does not work and must to change `/bin/bash`

**Comment by dougwettlaufer** [comment]
Hi @LordJohar, what operating system are you running this on? This works for me on macOS Mojave. What error did you get when you tried to run the script?

**Comment by jeffreyscarpenter** [comment]
Can't reproduce
