### ISSUE TITLE
Zeppelin Container Networking Broken

### ISSUE THREAD

**Issue by ds-steven-matison** [stargate/docker-images#61]
I was not able to get the docker zeppelin container, as documented [here](https://github.com/stargate/docker-images/tree/master/examples) to work with cassandra/stargate.  The error I got, regardless of cass interpreter configuration is:

`org.apache.zeppelin.interpreter.InterpreterException: com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/0.0.0.0:9044, hostId=null, hashCode=61178686): [com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s0|control|connecting...] Protocol initialization request, step 1 (OPTIONS): failed to send request (java.nio.channels.ClosedChannelException)]`

I was able to validate correct interpreter settings as follows:

- host: 0.0.0.0
-  port: 9044
- username: cassandra
- password: cassandra
- clustername: dse-6.8.9-cluster

and test with a binary copy of zeppelin on my local machine.  To support this Zeppelin on port 8080, I only had to modify my docker compose and change external mapping of 8080:8080 to 8085:8080

**Comment by polandll** [comment]
I'll work with Steven to get the right work done and submitted.
